version: '3'

services:
  mysql:
    # どのイメージを使用するか（DockerHubから選択）
    image: mysql:8.0
    # コンテナ作成時の名前
    container_name: myaql
    # データの保管&同期
    volumes:
      # docker-entrypoint-initdb.dはコンテナ作成時にSQLなどを実行できる
      - ./initdb:/docker-entrypoint-initdb.d
      # ホストとコンテナのファイル同期
      - ./data/mysql:/var/lib/mysql

    # ポートの番号紐付け
    ports:
      # ホスト:コンテナ
      - 3306:3306

    # 環境変数
    environment:
      MYSQL_DATABASE: whopay_database
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'

    # 再起動の設定
    restart: always

  api:
    # Dockerfileをもとにコンテナ作成
    build:
      # このファイルから見てDockerfileがどこにあるか
      context: .
      dockerfile: Dockerfile

    # コンテナ作成時の名前
    container_name: nest-graphql-api

    volumes:
      # ホストとコンテナのファイル同期
      - .:/app

    # 起動順を制御
    depends_on:
      # postgresが起動してからこのコンテナを起動
      - mysql

    # ポートの番号紐付け
    ports:
      - 4000:4000

    # 環境変数
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_SYNC: 'true'
      DATABASE_URL: mysql://root:password@mysql:3306/whopay_database

    # 再起動の設定
    restart: always
