version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitter_clone
    depends_on:
      - postgres
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      NODE_ENV: development
      DATABASE_URL: postgres://root:password@postgres:5432/

  postgres:
    image: postgres:13.1
    container_name: postgres
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      TZ: 'Asia/Tokyo'
    restart: always
